#!/bin/bash

args=""

whitespace="[[:space:]]"
for i in "$@"
do
    if [[ $i =~ $whitespace ]]
    then
        i=\"$i\"
    fi
    args=$args" $i"
done

if [[ -z "${args// }" ]]
then
    args="--help"
fi

result=`echo ${args} | nc -U /tmp/sand-glass-sock`
rc=$?

if [[ $rc != 0 ]]
then
	echo "SandGlass is not running"
	exit $rc;
fi

result=`echo ${result} | sed "s/^\([\"']\)\(.*\)\1\$/\2/g" | sed "s/u001b/033/g"`
echo -e "$result"
